### ISSUE TITLE
Mouse button click inconsistencies.

### ISSUE THREAD

**Issue by caumond** [sooneer/linkedin-queens-game#2]
When the mouse button is released outside the board, the event is lost.

So, when the mouse cursor is back in the board, it is continuing to spread crosses (x) as if the mouse button would be still pressed.

**Comment by sooneer** [comment]
Hi, Linkedin wanted close this site. I close this site But I created different design and name. I will fix this bug other site 
https://queens.bfn.tr

I did this app full open source: https://github.com/bfn-yazilim/queens 

I copied this note to the other side so as not to forget. Thank you very much. 

https://github.com/bfn-yazilim/queens/issues/1
